# Generated by Django 5.1.4 on 2026-06-13 14:07

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0002_seed_kpis_reports"),
        ("tenant", "0002_seed_default_tenant"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="dashboardwidget",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="dataexport",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="kpidefinition",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="kpisnapshot",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="reportdefinition",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="reportschedule",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="dashboardwidget",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="dataexport",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="historicaldashboardwidget",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="historicaldataexport",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="historicalkpidefinition",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="historicalkpisnapshot",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="historicalreportdefinition",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="historicalreportschedule",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="kpidefinition",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="kpisnapshot",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="reportdefinition",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="reportschedule",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenant.tenant",
            ),
        ),
    ]
