# Generated by Django 5.1.4 on 2026-05-19 23:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="APIEndpointStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("endpoint", models.CharField(max_length=500, unique=True)),
                ("method", models.CharField(max_length=10)),
                ("total_calls", models.PositiveIntegerField(default=0)),
                ("error_count", models.PositiveIntegerField(default=0)),
                ("avg_duration_ms", models.FloatField(default=0)),
                ("max_duration_ms", models.PositiveIntegerField(default=0)),
                ("min_duration_ms", models.PositiveIntegerField(default=0)),
                ("last_called", models.DateTimeField(blank=True, null=True)),
                ("last_status", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("is_degraded", models.BooleanField(default=False)),
                ("degraded_since", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Statut endpoint API",
                "verbose_name_plural": "Statuts endpoints API",
                "ordering": ["-total_calls"],
                "indexes": [
                    models.Index(fields=["endpoint"], name="monitoring__endpoin_c3a6f0_idx"),
                    models.Index(fields=["is_degraded"], name="monitoring__is_degr_ea9213_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="BusinessMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("API_CALLS", "Appels API"),
                            ("API_ERRORS", "Erreurs API"),
                            ("API_DURATION", "Temps de réponse moyen"),
                            ("ACTIVE_USERS", "Utilisateurs actifs"),
                            ("NEW_USERS", "Nouveaux utilisateurs"),
                            ("TOTAL_OBJECTS", "Nombre d'objets"),
                            ("WORKFLOW_COUNT", "Transitions workflow"),
                            ("EXPORT_COUNT", "Exports générés"),
                            ("STORAGE_USED", "Stockage utilisé"),
                            ("CACHE_HIT_RATE", "Taux de cache"),
                            ("CELERY_QUEUE", "File Celery"),
                            ("ERROR_COUNT", "Nombre d'erreurs"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "granularity",
                    models.CharField(
                        choices=[
                            ("1m", "1 minute"),
                            ("1h", "1 heure"),
                            ("24h", "24 heures"),
                            ("7d", "7 jours"),
                            ("30d", "30 jours"),
                        ],
                        default="1h",
                        max_length=5,
                    ),
                ),
                ("value", models.FloatField()),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Libellé optionnel (ex: endpoint name)",
                        max_length=100,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(db_index=True)),
            ],
            options={
                "verbose_name": "Métrique métier",
                "verbose_name_plural": "Métriques métier",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["metric_type", "granularity", "timestamp"],
                        name="monitoring__metric__137abf_idx",
                    ),
                    models.Index(fields=["-timestamp"], name="monitoring__timesta_9ad2e7_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("metric_type", "granularity", "label", "timestamp"),
                        name="uq_metric_grain_label_ts",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="APIRequestLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("method", models.CharField(max_length=10)),
                ("endpoint", models.CharField(max_length=500)),
                ("path", models.CharField(max_length=500)),
                ("query_params", models.JSONField(blank=True, default=dict)),
                ("status_code", models.PositiveSmallIntegerField()),
                ("duration_ms", models.PositiveIntegerField(help_text="Temps de réponse en ms")),
                ("response_size", models.PositiveIntegerField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("request_id", models.CharField(blank=True, max_length=100)),
                ("is_error", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Requête API",
                "verbose_name_plural": "Requêtes API",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["-timestamp"], name="monitoring__timesta_d0dba4_idx"),
                    models.Index(
                        fields=["method", "endpoint"], name="monitoring__method_11ac45_idx"
                    ),
                    models.Index(fields=["status_code"], name="monitoring__status__49ecfe_idx"),
                    models.Index(
                        fields=["is_error", "-timestamp"], name="monitoring__is_erro_3e6da3_idx"
                    ),
                    models.Index(
                        fields=["user", "-timestamp"], name="monitoring__user_id_bd5ca5_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SecurityEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("LOGIN_FAILED", "Échec connexion"),
                            ("LOGIN_SUCCESS", "Connexion réussie"),
                            ("LOGOUT", "Déconnexion"),
                            ("PERMISSION_DENIED", "Permission refusée"),
                            ("RATE_LIMITED", "Limite de débit atteinte"),
                            ("BRUTE_FORCE", "Attaque brute force"),
                            ("SUSPICIOUS_IP", "IP suspecte"),
                            ("SUSPICIOUS_ACTIVITY", "Activité suspecte"),
                            ("PASSWORD_CHANGED", "Mot de passe changé"),
                            ("ACCOUNT_LOCKED", "Compte verrouillé"),
                            ("ACCOUNT_UNLOCKED", "Compte déverrouillé"),
                            ("SESSION_EXPIRED", "Session expirée"),
                            ("API_ABUSE", "Abus API"),
                            ("DATA_EXPORT", "Export de données"),
                            ("SENSITIVE_ACCESS", "Accès données sensibles"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("INFO", "Information"),
                            ("LOW", "Faible"),
                            ("MEDIUM", "Moyen"),
                            ("HIGH", "Élevé"),
                            ("CRITICAL", "Critique"),
                        ],
                        default="INFO",
                        max_length=10,
                    ),
                ),
                ("user_email", models.EmailField(blank=True, max_length=254)),
                ("user_role", models.CharField(blank=True, max_length=20)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("endpoint", models.CharField(blank=True, max_length=500)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("action_taken", models.CharField(blank=True, max_length=200)),
                ("request_id", models.CharField(blank=True, max_length=100)),
                ("resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="security_events_resolved",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement sécurité",
                "verbose_name_plural": "Événements sécurité",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "-timestamp"], name="monitoring__event_t_76ac3e_idx"
                    ),
                    models.Index(
                        fields=["severity", "-timestamp"], name="monitoring__severit_d948b9_idx"
                    ),
                    models.Index(
                        fields=["user", "-timestamp"], name="monitoring__user_id_4125e3_idx"
                    ),
                    models.Index(
                        fields=["ip_address", "-timestamp"], name="monitoring__ip_addr_9b1c10_idx"
                    ),
                    models.Index(
                        fields=["resolved", "-timestamp"], name="monitoring__resolve_3f37c2_idx"
                    ),
                ],
            },
        ),
    ]
