# Generated by Django 5.1.4 on 2026-06-13 06:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("administration", "0004_seed_roles_permissions"),
        ("medical_coverage", "0004_voucher_amount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="approvalhistory",
            index=models.Index(fields=["action"], name="administrat_action_b1654b_idx"),
        ),
        migrations.AddIndex(
            model_name="approvalmatrix",
            index=models.Index(
                fields=["module", "is_active", "approval_level"],
                name="administrat_module_b24d79_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="permission",
            index=models.Index(fields=["module"], name="administrat_module_0e7d9d_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["is_active"], name="administrat_is_acti_2966a4_idx"),
        ),
        migrations.AddIndex(
            model_name="role",
            index=models.Index(fields=["rank"], name="administrat_rank_073b6f_idx"),
        ),
        migrations.AddIndex(
            model_name="userroleassignment",
            index=models.Index(fields=["is_active"], name="administrat_is_acti_bbf7b6_idx"),
        ),
        migrations.AddIndex(
            model_name="workflowpermission",
            index=models.Index(
                fields=["app_label", "model_name", "from_state", "to_state"],
                name="administrat_app_lab_22ed4e_idx",
            ),
        ),
    ]
