# Generated by Django 5.1.4 on 2026-06-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_historicaluser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("gestionnaire", "Gestionnaire RH"),
                    ("comptable", "Comptable"),
                    ("consultant", "Consultant"),
                    ("social_agent", "Agent Social"),
                    ("department_manager", "Chef de Service"),
                    ("committee_member", "Membre de Commission"),
                    ("director", "Directeur"),
                ],
                default="consultant",
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Administrateur"),
                    ("gestionnaire", "Gestionnaire RH"),
                    ("comptable", "Comptable"),
                    ("consultant", "Consultant"),
                    ("social_agent", "Agent Social"),
                    ("department_manager", "Chef de Service"),
                    ("committee_member", "Membre de Commission"),
                    ("director", "Directeur"),
                ],
                default="consultant",
                max_length=20,
                verbose_name="Rôle",
            ),
        ),
    ]
