# Generated by Django 5.1.4 on 2026-06-13 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0002_seed_default_tenant"),
        ("users", "0005_assign_default_tenant"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="user",
            new_name="users_user_tenant__79c011_idx",
            old_name="users_user_tenant_8c1ea0_idx",
        ),
        migrations.AlterField(
            model_name="historicaluser",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenant.tenant",
                verbose_name="Organisme",
            ),
        ),
    ]
