# Generated by Django 5.2.3 on 2026-05-19 22:07

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalNotification',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identifiant unique universel')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Date de dernière modification')),
                ('is_deleted', models.BooleanField(default=False, help_text='Suppression logique (soft delete)')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date de suppression logique', null=True)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('body', models.TextField(blank=True, verbose_name='Message')),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], default='in_app', max_length=10, verbose_name='Canal')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('critical', 'Critique')], default='medium', max_length=10, verbose_name='Priorité')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lue')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lue le')),
                ('action_url', models.URLField(blank=True, verbose_name='Lien action')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID objet')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('content_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contenttypes.contenttype', verbose_name='Type de contenu')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Utilisateur créateur', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Utilisateur ayant supprimé', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Dernier utilisateur modificateur', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Notification',
                'verbose_name_plural': 'historical Notifications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalNotificationPreference',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Identifiant unique universel')),
                ('created_at', models.DateTimeField(blank=True, editable=False, help_text='Date de création')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, help_text='Date de dernière modification')),
                ('is_deleted', models.BooleanField(default=False, help_text='Suppression logique (soft delete)')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date de suppression logique', null=True)),
                ('email_alerts', models.BooleanField(default=True, verbose_name='Notifications email')),
                ('sms_alerts', models.BooleanField(default=False, verbose_name='Notifications SMS')),
                ('push_alerts', models.BooleanField(default=False, verbose_name='Notifications push')),
                ('digest_frequency', models.CharField(choices=[('instant', 'Immédiat'), ('daily', 'Quotidien'), ('weekly', 'Hebdomadaire')], default='instant', max_length=10, verbose_name='Fréquence du digest')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='Début heures calmes')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Fin heures calmes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.TextField(null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Utilisateur créateur', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Utilisateur ayant supprimé', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Dernier utilisateur modificateur', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'historical Préférence notification',
                'verbose_name_plural': 'historical Préférences notifications',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('is_deleted', models.BooleanField(default=False, help_text='Suppression logique (soft delete)')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date de suppression logique', null=True)),
                ('email_alerts', models.BooleanField(default=True, verbose_name='Notifications email')),
                ('sms_alerts', models.BooleanField(default=False, verbose_name='Notifications SMS')),
                ('push_alerts', models.BooleanField(default=False, verbose_name='Notifications push')),
                ('digest_frequency', models.CharField(choices=[('instant', 'Immédiat'), ('daily', 'Quotidien'), ('weekly', 'Hebdomadaire')], default='instant', max_length=10, verbose_name='Fréquence du digest')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='Début heures calmes')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='Fin heures calmes')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('created_by', models.ForeignKey(blank=True, help_text='Utilisateur créateur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Utilisateur ayant supprimé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, help_text='Dernier utilisateur modificateur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Préférence notification',
                'verbose_name_plural': 'Préférences notifications',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Identifiant unique universel', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date de dernière modification')),
                ('is_deleted', models.BooleanField(default=False, help_text='Suppression logique (soft delete)')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Date de suppression logique', null=True)),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('body', models.TextField(blank=True, verbose_name='Message')),
                ('channel', models.CharField(choices=[('in_app', 'In-app'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], default='in_app', max_length=10, verbose_name='Canal')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('critical', 'Critique')], default='medium', max_length=10, verbose_name='Priorité')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lue')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Lue le')),
                ('action_url', models.URLField(blank=True, verbose_name='Lien action')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID objet')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Type de contenu')),
                ('created_by', models.ForeignKey(blank=True, help_text='Utilisateur créateur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, help_text='Utilisateur ayant supprimé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Dernier utilisateur modificateur', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_a972ce_idx'), models.Index(fields=['priority', 'is_read'], name='notificatio_priorit_60753b_idx')],
            },
        ),
    ]
