# Generated by Django 5.1.4 on 2026-06-13 17:32

import django.db.models.deletion
import shared.documents.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "Général"),
                            ("contract", "Contrat"),
                            ("report", "Rapport"),
                            ("invoice", "Facture"),
                            ("medical", "Médical"),
                            ("admin", "Administratif"),
                            ("other", "Autre"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(upload_to=shared.documents.models.document_upload_path)),
                ("file_name", models.CharField(blank=True, max_length=500)),
                ("file_size_bytes", models.PositiveIntegerField(blank=True, null=True)),
                ("file_type", models.CharField(blank=True, max_length=50)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_deleted", models.BooleanField(default=False)),
                ("related_entity_type", models.CharField(blank=True, max_length=50)),
                ("related_entity_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["category"], name="shared_docu_categor_0ac3bb_idx"),
                    models.Index(fields=["is_deleted"], name="shared_docu_is_dele_2d6ef4_idx"),
                ],
            },
        ),
    ]
