# Generated by Django 5.1.4 on 2026-05-19 20:52

import apps.benefits.models
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("beneficiaries", "__first__"),
        ("employees", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Benefit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Date de dernière modification"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                ("workflow_state", models.CharField(db_index=True, max_length=50)),
                ("workflow_updated_at", models.DateTimeField(blank=True, null=True)),
                ("last_transition_at", models.DateTimeField(blank=True, null=True)),
                ("last_transition_reason", models.TextField(blank=True)),
                (
                    "reference",
                    models.CharField(
                        editable=False, max_length=30, unique=True, verbose_name="Référence"
                    ),
                ),
                (
                    "requested_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Montant demandé (DZD)"
                    ),
                ),
                (
                    "approved_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Montant approuvé (DZD)",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Montant payé (DZD)",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Objet de la demande")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description / Justification"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Basse"),
                            ("normal", "Normale"),
                            ("high", "Haute"),
                            ("urgent", "Urgente"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date de soumission"),
                ),
                (
                    "validated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date de validation"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date de paiement"),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date de rejet"),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'échéance souhaitée"
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, verbose_name="Motif de rejet")),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence de paiement"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("virement", "Virement bancaire"),
                            ("cheque", "Chèque"),
                            ("caisse", "Caisse"),
                            ("ccp", "CCP"),
                        ],
                        max_length=20,
                        verbose_name="Mode de paiement",
                    ),
                ),
                (
                    "analytics_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Timestamps et durées par état — dataset ML",
                        verbose_name="Données analytiques",
                    ),
                ),
                (
                    "ai_score",
                    models.FloatField(
                        blank=True,
                        help_text="Score de la demande calculé par le moteur AI",
                        null=True,
                        verbose_name="Score AI",
                    ),
                ),
                (
                    "ai_anomaly_flag",
                    models.BooleanField(
                        default=False,
                        help_text="True si le moteur AI a détecté une anomalie",
                        verbose_name="Anomalie détectée AI",
                    ),
                ),
                (
                    "risk_score",
                    models.FloatField(
                        blank=True,
                        help_text="Score de risque calculé (0-100)",
                        null=True,
                        verbose_name="Score de risque",
                    ),
                ),
                (
                    "ai_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Résultats et recommandations du moteur AI",
                        verbose_name="Métadonnées AI",
                    ),
                ),
                ("internal_notes", models.TextField(blank=True, verbose_name="Notes internes")),
                (
                    "beneficiary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="benefits",
                        to="beneficiaries.beneficiary",
                        verbose_name="Ayant droit concerné",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="benefits",
                        to="employees.employee",
                        verbose_name="Employé",
                    ),
                ),
                (
                    "last_transition_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_last_transitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paid_benefits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Payé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_benefits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prestation",
                "verbose_name_plural": "Prestations",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BenefitAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Date de dernière modification"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.benefits.models.attachment_upload_path,
                        verbose_name="Fichier",
                    ),
                ),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="Nom original du fichier"),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("prescription", "Ordonnance médicale"),
                            ("invoice", "Facture"),
                            ("certificate", "Certificat"),
                            ("identity", "Pièce d'identité"),
                            ("salary_slip", "Bulletin de salaire"),
                            ("bank_details", "RIB bancaire"),
                            ("other", "Autre document"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, verbose_name="Description"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, verbose_name="Taille (octets)"),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                (
                    "benefit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="benefits.benefit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce jointe",
                "verbose_name_plural": "Pièces jointes",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="BenefitComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Date de dernière modification"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("internal", "Note interne"),
                            ("requester", "Message au demandeur"),
                            ("system", "Message système"),
                        ],
                        default="internal",
                        max_length=15,
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenu")),
                ("workflow_state_at_time", models.CharField(blank=True, max_length=50)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="benefit_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "benefit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="benefits.benefit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Commentaire",
                "verbose_name_plural": "Commentaires",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="BenefitType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Date de dernière modification"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True, verbose_name="Code")),
                ("name", models.CharField(max_length=150, verbose_name="Libellé")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("medical", "Prise en charge médicale"),
                            ("loan", "Prêt"),
                            ("purchase", "Achat facilité"),
                            ("bonus", "Prime"),
                            ("aid", "Aide exceptionnelle"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Montant plafond (DZD)",
                    ),
                ),
                (
                    "min_seniority_years",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ancienneté minimale (années)"
                    ),
                ),
                (
                    "max_per_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Nb max par an et par employé"
                    ),
                ),
                (
                    "requires_attachments",
                    models.BooleanField(
                        default=False, verbose_name="Pièces justificatives obligatoires"
                    ),
                ),
                (
                    "required_attachments_description",
                    models.TextField(blank=True, verbose_name="Description des pièces requises"),
                ),
                (
                    "target_processing_days",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Délai cible (jours)"
                    ),
                ),
                (
                    "ai_processing_hints",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Hints pour le moteur AI futur"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Type de prestation",
                "verbose_name_plural": "Types de prestations",
                "ordering": ["category", "name"],
            },
        ),
        migrations.AddField(
            model_name="benefit",
            name="benefit_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="benefits",
                to="benefits.benefittype",
                verbose_name="Type de prestation",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalBenefit",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, help_text="Date de dernière modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                ("workflow_state", models.CharField(db_index=True, max_length=50)),
                ("workflow_updated_at", models.DateTimeField(blank=True, null=True)),
                ("last_transition_at", models.DateTimeField(blank=True, null=True)),
                ("last_transition_reason", models.TextField(blank=True)),
                (
                    "reference",
                    models.CharField(
                        db_index=True, editable=False, max_length=30, verbose_name="Référence"
                    ),
                ),
                (
                    "requested_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Montant demandé (DZD)"
                    ),
                ),
                (
                    "approved_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Montant approuvé (DZD)",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Montant payé (DZD)",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Objet de la demande")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description / Justification"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Basse"),
                            ("normal", "Normale"),
                            ("high", "Haute"),
                            ("urgent", "Urgente"),
                        ],
                        default="normal",
                        max_length=10,
                        verbose_name="Priorité",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date de soumission"),
                ),
                (
                    "validated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date de validation"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date de paiement"),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date de rejet"),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date d'échéance souhaitée"
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, verbose_name="Motif de rejet")),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence de paiement"
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("virement", "Virement bancaire"),
                            ("cheque", "Chèque"),
                            ("caisse", "Caisse"),
                            ("ccp", "CCP"),
                        ],
                        max_length=20,
                        verbose_name="Mode de paiement",
                    ),
                ),
                (
                    "analytics_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Timestamps et durées par état — dataset ML",
                        verbose_name="Données analytiques",
                    ),
                ),
                (
                    "ai_score",
                    models.FloatField(
                        blank=True,
                        help_text="Score de la demande calculé par le moteur AI",
                        null=True,
                        verbose_name="Score AI",
                    ),
                ),
                (
                    "ai_anomaly_flag",
                    models.BooleanField(
                        default=False,
                        help_text="True si le moteur AI a détecté une anomalie",
                        verbose_name="Anomalie détectée AI",
                    ),
                ),
                (
                    "risk_score",
                    models.FloatField(
                        blank=True,
                        help_text="Score de risque calculé (0-100)",
                        null=True,
                        verbose_name="Score de risque",
                    ),
                ),
                (
                    "ai_metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Résultats et recommandations du moteur AI",
                        verbose_name="Métadonnées AI",
                    ),
                ),
                ("internal_notes", models.TextField(blank=True, verbose_name="Notes internes")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="beneficiaries.beneficiary",
                        verbose_name="Ayant droit concerné",
                    ),
                ),
                (
                    "benefit_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="benefits.benefittype",
                        verbose_name="Type de prestation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="employees.employee",
                        verbose_name="Employé",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_transition_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Payé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Prestation",
                "verbose_name_plural": "historical Prestations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBenefitAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, help_text="Date de dernière modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                ("file", models.TextField(max_length=100, verbose_name="Fichier")),
                (
                    "original_name",
                    models.CharField(max_length=255, verbose_name="Nom original du fichier"),
                ),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("prescription", "Ordonnance médicale"),
                            ("invoice", "Facture"),
                            ("certificate", "Certificat"),
                            ("identity", "Pièce d'identité"),
                            ("salary_slip", "Bulletin de salaire"),
                            ("bank_details", "RIB bancaire"),
                            ("other", "Autre document"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, verbose_name="Description"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, verbose_name="Taille (octets)"),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "benefit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="benefits.benefit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Pièce jointe",
                "verbose_name_plural": "historical Pièces jointes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBenefitComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, help_text="Date de dernière modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("internal", "Note interne"),
                            ("requester", "Message au demandeur"),
                            ("system", "Message système"),
                        ],
                        default="internal",
                        max_length=15,
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenu")),
                ("workflow_state_at_time", models.CharField(blank=True, max_length=50)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "benefit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="benefits.benefit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Commentaire",
                "verbose_name_plural": "historical Commentaires",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalBenefitType",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, help_text="Date de dernière modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=30, verbose_name="Code")),
                ("name", models.CharField(max_length=150, verbose_name="Libellé")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("medical", "Prise en charge médicale"),
                            ("loan", "Prêt"),
                            ("purchase", "Achat facilité"),
                            ("bonus", "Prime"),
                            ("aid", "Aide exceptionnelle"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "max_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Montant plafond (DZD)",
                    ),
                ),
                (
                    "min_seniority_years",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Ancienneté minimale (années)"
                    ),
                ),
                (
                    "max_per_year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Nb max par an et par employé"
                    ),
                ),
                (
                    "requires_attachments",
                    models.BooleanField(
                        default=False, verbose_name="Pièces justificatives obligatoires"
                    ),
                ),
                (
                    "required_attachments_description",
                    models.TextField(blank=True, verbose_name="Description des pièces requises"),
                ),
                (
                    "target_processing_days",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Délai cible (jours)"
                    ),
                ),
                (
                    "ai_processing_hints",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Hints pour le moteur AI futur"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Type de prestation",
                "verbose_name_plural": "historical Types de prestations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name="benefittype",
            index=models.Index(fields=["code"], name="benefits_be_code_e3e674_idx"),
        ),
        migrations.AddIndex(
            model_name="benefittype",
            index=models.Index(
                fields=["category", "is_active"], name="benefits_be_categor_753df9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="benefit",
            index=models.Index(fields=["reference"], name="benefits_be_referen_1c892d_idx"),
        ),
        migrations.AddIndex(
            model_name="benefit",
            index=models.Index(fields=["workflow_state"], name="benefits_be_workflo_2922e6_idx"),
        ),
        migrations.AddIndex(
            model_name="benefit",
            index=models.Index(
                fields=["employee", "workflow_state"], name="benefits_be_employe_d567ff_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="benefit",
            index=models.Index(
                fields=["benefit_type", "workflow_state"], name="benefits_be_benefit_b843f6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="benefit",
            index=models.Index(fields=["submitted_at"], name="benefits_be_submitt_3c300b_idx"),
        ),
        migrations.AddIndex(
            model_name="benefit",
            index=models.Index(
                fields=["priority", "workflow_state"], name="benefits_be_priorit_57f12a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="benefit",
            index=models.Index(fields=["ai_anomaly_flag"], name="benefits_be_ai_anom_2025d7_idx"),
        ),
    ]
