# Generated by Django 5.1.4 on 2026-06-10 19:20

import django.db.models.deletion
import django.db.models.manager
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0004_beneficiary_address_beneficiary_phone_and_more"),
        ("conventions", "0002_alter_convention_managers_and_more"),
        ("employees", "0002_alter_employee_managers"),
        ("medical_coverage", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalMedicalCoverageRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, help_text="Date de dernière modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                ("workflow_updated_at", models.DateTimeField(blank=True, null=True)),
                ("last_transition_at", models.DateTimeField(blank=True, null=True)),
                ("last_transition_reason", models.TextField(blank=True)),
                (
                    "request_number",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=50,
                        verbose_name="Numéro de demande",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("analysis", "Medical Analysis"),
                            ("imaging", "Medical Imaging"),
                            ("center", "Medical Center"),
                        ],
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                ("coverage_date", models.DateField(verbose_name="Date de couverture")),
                (
                    "validation_date",
                    models.DateField(blank=True, null=True, verbose_name="Date de validation"),
                ),
                ("observation", models.TextField(blank=True, verbose_name="Observation")),
                (
                    "workflow_state",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("submitted", "Soumise"),
                            ("pending_approval", "En attente d'approbation"),
                            ("validated", "Validée"),
                            ("rejected", "Rejetée"),
                            ("printed", "Imprimée"),
                            ("closed", "Clôturée"),
                        ],
                        default="draft",
                        max_length=30,
                        verbose_name="Statut",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="beneficiaries.beneficiary",
                        verbose_name="Ayant droit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="employees.employee",
                        verbose_name="Employé",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_transition_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="conventions.partner",
                        verbose_name="Partenaire",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Demande de couverture médicale",
                "verbose_name_plural": "historical Demandes de couverture médicale",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="MedicalCoverageRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Date de dernière modification"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                ("workflow_updated_at", models.DateTimeField(blank=True, null=True)),
                ("last_transition_at", models.DateTimeField(blank=True, null=True)),
                ("last_transition_reason", models.TextField(blank=True)),
                (
                    "request_number",
                    models.CharField(
                        editable=False, max_length=50, unique=True, verbose_name="Numéro de demande"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("analysis", "Medical Analysis"),
                            ("imaging", "Medical Imaging"),
                            ("center", "Medical Center"),
                        ],
                        max_length=20,
                        verbose_name="Catégorie",
                    ),
                ),
                ("coverage_date", models.DateField(verbose_name="Date de couverture")),
                (
                    "validation_date",
                    models.DateField(blank=True, null=True, verbose_name="Date de validation"),
                ),
                ("observation", models.TextField(blank=True, verbose_name="Observation")),
                (
                    "workflow_state",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("submitted", "Soumise"),
                            ("pending_approval", "En attente d'approbation"),
                            ("validated", "Validée"),
                            ("rejected", "Rejetée"),
                            ("printed", "Imprimée"),
                            ("closed", "Clôturée"),
                        ],
                        default="draft",
                        max_length=30,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "beneficiary",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coverage_requests",
                        to="beneficiaries.beneficiary",
                        verbose_name="Ayant droit",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coverage_requests",
                        to="employees.employee",
                        verbose_name="Employé",
                    ),
                ),
                (
                    "last_transition_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_last_transitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="coverage_requests",
                        to="conventions.partner",
                        verbose_name="Partenaire",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de couverture médicale",
                "verbose_name_plural": "Demandes de couverture médicale",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["request_number"], name="medical_cov_request_e7cdb6_idx"),
                    models.Index(
                        fields=["category", "workflow_state"], name="medical_cov_categor_563eef_idx"
                    ),
                    models.Index(
                        fields=["employee", "coverage_date"], name="medical_cov_employe_0025ea_idx"
                    ),
                ],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
    ]
