# Generated by Django 5.1.4 on 2026-06-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_coverage", "0002_historicalmedicalcoveragerequest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalmedicalcoveragerequest",
            name="workflow_state",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("submitted", "Soumise"),
                    ("pending_approval", "En attente d'approbation"),
                    ("pending_manager_approval", "En attente du chef de service"),
                    ("pending_director_approval", "En attente du directeur"),
                    ("validated", "Validée"),
                    ("rejected", "Rejetée"),
                    ("printed", "Imprimée"),
                    ("closed", "Clôturée"),
                ],
                default="draft",
                max_length=30,
                verbose_name="Statut",
            ),
        ),
        migrations.AlterField(
            model_name="medicalcoveragerequest",
            name="workflow_state",
            field=models.CharField(
                choices=[
                    ("draft", "Brouillon"),
                    ("submitted", "Soumise"),
                    ("pending_approval", "En attente d'approbation"),
                    ("pending_manager_approval", "En attente du chef de service"),
                    ("pending_director_approval", "En attente du directeur"),
                    ("validated", "Validée"),
                    ("rejected", "Rejetée"),
                    ("printed", "Imprimée"),
                    ("closed", "Clôturée"),
                ],
                default="draft",
                max_length=30,
                verbose_name="Statut",
            ),
        ),
    ]
