# Generated by Django 5.1.4 on 2026-06-13 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("medical_coverage", "0004_voucher_amount"),
        ("tenant", "0002_seed_default_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalmedicalcoveragerequest",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="historicalmedicalcoveragetype",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="historicalmedicalcoveragevoucher",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="historicalmedicalprovider",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="medicalcoveragerequest",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="medicalcoveragetype",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="medicalcoveragevoucher",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="medicalprovider",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenant.tenant",
            ),
        ),
    ]
