# Generated by Django 5.1.4 on 2026-05-19 20:52

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("benefits", "0001_initial"),
        ("departments", "__first__"),
        ("employees", "__first__"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Date de dernière modification"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                ("code", models.CharField(max_length=30, unique=True, verbose_name="Code budget")),
                ("label", models.CharField(max_length=200, verbose_name="Libellé")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("approved", "Approuvé"),
                            ("active", "Actif"),
                            ("closed", "Clôturé"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Montant alloué (DZD)"
                    ),
                ),
                (
                    "committed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="Montant engagé (DZD)",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="Montant payé (DZD)",
                    ),
                ),
                (
                    "reserved_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="Montant réservé (DZD)",
                    ),
                ),
                (
                    "alert_threshold_pct",
                    models.PositiveSmallIntegerField(
                        default=80,
                        help_text="Déclenche une alerte quand la consommation dépasse ce seuil",
                        verbose_name="Seuil d'alerte (%)",
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "variance_percent",
                    models.FloatField(
                        blank=True, help_text="Écart budget vs réel (%) — feature ML", null=True
                    ),
                ),
                (
                    "anomaly_score",
                    models.FloatField(
                        blank=True, help_text="Score d'anomalie IA (0-100)", null=True
                    ),
                ),
                (
                    "prediction_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Prévisions et recommandations IA"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_budgets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "benefit_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budgets",
                        to="benefits.benefittype",
                        verbose_name="Type de prestation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="budgets",
                        to="departments.department",
                        verbose_name="Département",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget",
                "verbose_name_plural": "Budgets",
                "ordering": ["fiscal_year__year", "code"],
            },
        ),
        migrations.CreateModel(
            name="FiscalYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Date de dernière modification"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(unique=True, verbose_name="Année")),
                ("label", models.CharField(max_length=100, verbose_name="Libellé")),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("open", "Ouvert"),
                            ("closed", "Clôturé"),
                            ("archived", "Archivé"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "total_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="Budget total (DZD)",
                    ),
                ),
                (
                    "total_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="Total payé (DZD)",
                    ),
                ),
                (
                    "total_committed",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="Total engagé (DZD)",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "prediction_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Prévisions budgétaires AI pour l'année suivante",
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="closed_fiscal_years",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Exercice fiscal",
                "verbose_name_plural": "Exercices fiscaux",
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="FinancialEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Date de dernière modification"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                (
                    "entry_number",
                    models.CharField(
                        editable=False, max_length=30, unique=True, verbose_name="N° écriture"
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("debit", "Débit"),
                            ("credit", "Crédit"),
                            ("adjustment", "Ajustement"),
                            ("reversal", "Annulation (écriture inverse)"),
                            ("opening", "À-nouveau d'ouverture"),
                            ("closing", "Clôture"),
                        ],
                        max_length=15,
                    ),
                ),
                ("label", models.CharField(max_length=300, verbose_name="Libellé")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "entry_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date d'écriture"
                    ),
                ),
                (
                    "accounting_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date comptable"
                    ),
                ),
                (
                    "debit_account",
                    models.CharField(blank=True, max_length=20, verbose_name="Compte débité"),
                ),
                (
                    "credit_account",
                    models.CharField(blank=True, max_length=20, verbose_name="Compte crédité"),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "budget",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="accounting_entries",
                        to="finance.budget",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="accounting_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversed_entry",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reversals",
                        to="finance.financialentry",
                        verbose_name="Écriture annulée",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="finance.fiscalyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "Écriture comptable",
                "verbose_name_plural": "Écritures comptables",
                "ordering": ["-entry_date", "-entry_number"],
            },
        ),
        migrations.AddField(
            model_name="budget",
            name="fiscal_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="budgets",
                to="finance.fiscalyear",
                verbose_name="Exercice fiscal",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalBudget",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, help_text="Date de dernière modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                (
                    "code",
                    models.CharField(db_index=True, max_length=30, verbose_name="Code budget"),
                ),
                ("label", models.CharField(max_length=200, verbose_name="Libellé")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("approved", "Approuvé"),
                            ("active", "Actif"),
                            ("closed", "Clôturé"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "allocated_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Montant alloué (DZD)"
                    ),
                ),
                (
                    "committed_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="Montant engagé (DZD)",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="Montant payé (DZD)",
                    ),
                ),
                (
                    "reserved_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=15,
                        verbose_name="Montant réservé (DZD)",
                    ),
                ),
                (
                    "alert_threshold_pct",
                    models.PositiveSmallIntegerField(
                        default=80,
                        help_text="Déclenche une alerte quand la consommation dépasse ce seuil",
                        verbose_name="Seuil d'alerte (%)",
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "variance_percent",
                    models.FloatField(
                        blank=True, help_text="Écart budget vs réel (%) — feature ML", null=True
                    ),
                ),
                (
                    "anomaly_score",
                    models.FloatField(
                        blank=True, help_text="Score d'anomalie IA (0-100)", null=True
                    ),
                ),
                (
                    "prediction_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Prévisions et recommandations IA"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "benefit_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="benefits.benefittype",
                        verbose_name="Type de prestation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="departments.department",
                        verbose_name="Département",
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.fiscalyear",
                        verbose_name="Exercice fiscal",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Budget",
                "verbose_name_plural": "historical Budgets",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFiscalYear",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, help_text="Date de dernière modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                ("year", models.PositiveSmallIntegerField(db_index=True, verbose_name="Année")),
                ("label", models.CharField(max_length=100, verbose_name="Libellé")),
                ("start_date", models.DateField(verbose_name="Date de début")),
                ("end_date", models.DateField(verbose_name="Date de fin")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("open", "Ouvert"),
                            ("closed", "Clôturé"),
                            ("archived", "Archivé"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "total_budget",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="Budget total (DZD)",
                    ),
                ),
                (
                    "total_paid",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="Total payé (DZD)",
                    ),
                ),
                (
                    "total_committed",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=18,
                        verbose_name="Total engagé (DZD)",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "prediction_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Prévisions budgétaires AI pour l'année suivante",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "closed_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Exercice fiscal",
                "verbose_name_plural": "historical Exercices fiscaux",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalPaymentBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, help_text="Date de dernière modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                ("reference", models.CharField(db_index=True, editable=False, max_length=30)),
                ("label", models.CharField(max_length=200, verbose_name="Libellé du lot")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("submitted", "Soumis"),
                            ("approved", "Approuvé"),
                            ("sent", "Envoyé à la banque"),
                            ("confirmed", "Confirmé par la banque"),
                            ("rejected", "Rejeté"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("virement", "Virement bancaire"),
                            ("cheque", "Chèque"),
                            ("caisse", "Caisse"),
                            ("ccp", "CCP"),
                        ],
                        default="virement",
                        max_length=20,
                        verbose_name="Mode de paiement",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                ("payment_count", models.PositiveIntegerField(default=0)),
                (
                    "scheduled_date",
                    models.DateField(blank=True, null=True, verbose_name="Date d'exécution prévue"),
                ),
                (
                    "executed_date",
                    models.DateField(blank=True, null=True, verbose_name="Date d'exécution réelle"),
                ),
                (
                    "bank_reference",
                    models.CharField(blank=True, max_length=100, verbose_name="Référence bancaire"),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.fiscalyear",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Lot de paiements",
                "verbose_name_plural": "historical Lots de paiements",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Date de dernière modification"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                ("reference", models.CharField(editable=False, max_length=30, unique=True)),
                (
                    "beneficiary_name",
                    models.CharField(blank=True, max_length=200, verbose_name="Nom bénéficiaire"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Montant (DZD)"
                    ),
                ),
                (
                    "fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Frais bancaires (DZD)",
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Montant net (DZD)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvé"),
                            ("processing", "En traitement"),
                            ("paid", "Payé"),
                            ("failed", "Échoué"),
                            ("cancelled", "Annulé"),
                            ("reversed", "Annulé par écriture inverse"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("virement", "Virement"),
                            ("cheque", "Chèque"),
                            ("caisse", "Caisse"),
                            ("ccp", "CCP"),
                        ],
                        default="virement",
                        max_length=20,
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(blank=True, max_length=50, verbose_name="RIB / CCP"),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100, verbose_name="Banque")),
                (
                    "bank_reference",
                    models.CharField(blank=True, max_length=100, verbose_name="Référence bancaire"),
                ),
                (
                    "scheduled_date",
                    models.DateField(blank=True, null=True, verbose_name="Date d'exécution prévue"),
                ),
                (
                    "executed_date",
                    models.DateField(blank=True, null=True, verbose_name="Date d'exécution réelle"),
                ),
                (
                    "value_date",
                    models.DateField(blank=True, null=True, verbose_name="Date de valeur"),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accounting_entry",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="N° écriture comptable"
                    ),
                ),
                (
                    "cost_center",
                    models.CharField(blank=True, max_length=50, verbose_name="Centre de coût"),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "anomaly_flag",
                    models.BooleanField(default=False, help_text="Anomalie détectée par l'IA"),
                ),
                (
                    "anomaly_score",
                    models.FloatField(blank=True, help_text="Score d'anomalie (0-100)", null=True),
                ),
                (
                    "risk_indicators",
                    models.JSONField(
                        blank=True, default=dict, help_text="Indicateurs de risque IA"
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "benefit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payment_record",
                        to="benefits.benefit",
                        verbose_name="Prestation",
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="finance.budget",
                        verbose_name="Budget",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="employees.employee",
                        verbose_name="Employé",
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="finance.fiscalyear",
                        verbose_name="Exercice",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Paiement",
                "verbose_name_plural": "Paiements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalFinancialEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, help_text="Date de dernière modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                (
                    "entry_number",
                    models.CharField(
                        db_index=True, editable=False, max_length=30, verbose_name="N° écriture"
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("debit", "Débit"),
                            ("credit", "Crédit"),
                            ("adjustment", "Ajustement"),
                            ("reversal", "Annulation (écriture inverse)"),
                            ("opening", "À-nouveau d'ouverture"),
                            ("closing", "Clôture"),
                        ],
                        max_length=15,
                    ),
                ),
                ("label", models.CharField(max_length=300, verbose_name="Libellé")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=18)),
                (
                    "entry_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date d'écriture"
                    ),
                ),
                (
                    "accounting_date",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Date comptable"
                    ),
                ),
                (
                    "debit_account",
                    models.CharField(blank=True, max_length=20, verbose_name="Compte débité"),
                ),
                (
                    "credit_account",
                    models.CharField(blank=True, max_length=20, verbose_name="Compte crédité"),
                ),
                ("notes", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.budget",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by_user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.fiscalyear",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reversed_entry",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.financialentry",
                        verbose_name="Écriture annulée",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Écriture comptable",
                "verbose_name_plural": "historical Écritures comptables",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalFinancialAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, help_text="Date de dernière modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("budget_threshold", "Seuil budgétaire atteint"),
                            ("budget_overrun", "Dépassement budgétaire"),
                            ("anomaly_detected", "Anomalie détectée"),
                            ("large_payment", "Paiement élevé"),
                            ("duplicate_payment", "Doublon potentiel"),
                            ("fiscal_year_end", "Fin d'exercice proche"),
                            ("sla_breach", "Dépassement délai SLA"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Avertissement"),
                            ("critical", "Critique"),
                        ],
                        default="warning",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ai_generated",
                    models.BooleanField(default=False, help_text="Générée par le moteur AI"),
                ),
                (
                    "ai_confidence",
                    models.FloatField(
                        blank=True, help_text="Confiance du modèle AI (0-1)", null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.budget",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.fiscalyear",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Alerte financière",
                "verbose_name_plural": "historical Alertes financières",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddField(
            model_name="financialentry",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="accounting_entries",
                to="finance.payment",
            ),
        ),
        migrations.CreateModel(
            name="FinancialAlert",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Date de dernière modification"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                (
                    "alert_type",
                    models.CharField(
                        choices=[
                            ("budget_threshold", "Seuil budgétaire atteint"),
                            ("budget_overrun", "Dépassement budgétaire"),
                            ("anomaly_detected", "Anomalie détectée"),
                            ("large_payment", "Paiement élevé"),
                            ("duplicate_payment", "Doublon potentiel"),
                            ("fiscal_year_end", "Fin d'exercice proche"),
                            ("sla_breach", "Dépassement délai SLA"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Information"),
                            ("warning", "Avertissement"),
                            ("critical", "Critique"),
                        ],
                        default="warning",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "ai_generated",
                    models.BooleanField(default=False, help_text="Générée par le moteur AI"),
                ),
                (
                    "ai_confidence",
                    models.FloatField(
                        blank=True, help_text="Confiance du modèle AI (0-1)", null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "budget",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.budget",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.fiscalyear",
                    ),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="finance.payment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Alerte financière",
                "verbose_name_plural": "Alertes financières",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Date de dernière modification"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                ("reference", models.CharField(editable=False, max_length=30, unique=True)),
                ("label", models.CharField(max_length=200, verbose_name="Libellé du lot")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Brouillon"),
                            ("submitted", "Soumis"),
                            ("approved", "Approuvé"),
                            ("sent", "Envoyé à la banque"),
                            ("confirmed", "Confirmé par la banque"),
                            ("rejected", "Rejeté"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("virement", "Virement bancaire"),
                            ("cheque", "Chèque"),
                            ("caisse", "Caisse"),
                            ("ccp", "CCP"),
                        ],
                        default="virement",
                        max_length=20,
                        verbose_name="Mode de paiement",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=18),
                ),
                ("payment_count", models.PositiveIntegerField(default=0)),
                (
                    "scheduled_date",
                    models.DateField(blank=True, null=True, verbose_name="Date d'exécution prévue"),
                ),
                (
                    "executed_date",
                    models.DateField(blank=True, null=True, verbose_name="Date d'exécution réelle"),
                ),
                (
                    "bank_reference",
                    models.CharField(blank=True, max_length=100, verbose_name="Référence bancaire"),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="finance.fiscalyear",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lot de paiements",
                "verbose_name_plural": "Lots de paiements",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="payment",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="finance.paymentbatch",
                verbose_name="Lot de paiement",
            ),
        ),
        migrations.CreateModel(
            name="HistoricalPayment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, help_text="Date de dernière modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                ("reference", models.CharField(db_index=True, editable=False, max_length=30)),
                (
                    "beneficiary_name",
                    models.CharField(blank=True, max_length=200, verbose_name="Nom bénéficiaire"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Montant (DZD)"
                    ),
                ),
                (
                    "fees",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Frais bancaires (DZD)",
                    ),
                ),
                (
                    "net_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=14,
                        verbose_name="Montant net (DZD)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("approved", "Approuvé"),
                            ("processing", "En traitement"),
                            ("paid", "Payé"),
                            ("failed", "Échoué"),
                            ("cancelled", "Annulé"),
                            ("reversed", "Annulé par écriture inverse"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("virement", "Virement"),
                            ("cheque", "Chèque"),
                            ("caisse", "Caisse"),
                            ("ccp", "CCP"),
                        ],
                        default="virement",
                        max_length=20,
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(blank=True, max_length=50, verbose_name="RIB / CCP"),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100, verbose_name="Banque")),
                (
                    "bank_reference",
                    models.CharField(blank=True, max_length=100, verbose_name="Référence bancaire"),
                ),
                (
                    "scheduled_date",
                    models.DateField(blank=True, null=True, verbose_name="Date d'exécution prévue"),
                ),
                (
                    "executed_date",
                    models.DateField(blank=True, null=True, verbose_name="Date d'exécution réelle"),
                ),
                (
                    "value_date",
                    models.DateField(blank=True, null=True, verbose_name="Date de valeur"),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "accounting_entry",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="N° écriture comptable"
                    ),
                ),
                (
                    "cost_center",
                    models.CharField(blank=True, max_length=50, verbose_name="Centre de coût"),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "anomaly_flag",
                    models.BooleanField(default=False, help_text="Anomalie détectée par l'IA"),
                ),
                (
                    "anomaly_score",
                    models.FloatField(blank=True, help_text="Score d'anomalie (0-100)", null=True),
                ),
                (
                    "risk_indicators",
                    models.JSONField(
                        blank=True, default=dict, help_text="Indicateurs de risque IA"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "benefit",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="benefits.benefit",
                        verbose_name="Prestation",
                    ),
                ),
                (
                    "budget",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.budget",
                        verbose_name="Budget",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="employees.employee",
                        verbose_name="Employé",
                    ),
                ),
                (
                    "fiscal_year",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.fiscalyear",
                        verbose_name="Exercice",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="finance.paymentbatch",
                        verbose_name="Lot de paiement",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Paiement",
                "verbose_name_plural": "historical Paiements",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["fiscal_year", "status"], name="finance_bud_fiscal__644a79_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["benefit_type", "fiscal_year"], name="finance_bud_benefit_5c9b60_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="budget",
            index=models.Index(
                fields=["department", "fiscal_year"], name="finance_bud_departm_8603d3_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="budget",
            constraint=models.UniqueConstraint(
                condition=models.Q(("benefit_type__isnull", False), ("department__isnull", False)),
                fields=("fiscal_year", "benefit_type", "department"),
                name="unique_budget_per_type_dept_year",
            ),
        ),
        migrations.AddIndex(
            model_name="financialentry",
            index=models.Index(
                fields=["fiscal_year", "entry_date"], name="finance_fin_fiscal__782a03_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialentry",
            index=models.Index(fields=["entry_type"], name="finance_fin_entry_t_296ed9_idx"),
        ),
        migrations.AddIndex(
            model_name="financialentry",
            index=models.Index(fields=["payment"], name="finance_fin_payment_074bbe_idx"),
        ),
        migrations.AddIndex(
            model_name="financialalert",
            index=models.Index(
                fields=["severity", "is_resolved"], name="finance_fin_severit_3f73ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialalert",
            index=models.Index(
                fields=["alert_type", "is_resolved"], name="finance_fin_alert_t_59338c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="financialalert",
            index=models.Index(
                fields=["fiscal_year", "is_resolved"], name="finance_fin_fiscal__78f411_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["status"], name="finance_pay_status_cb601d_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["employee", "status"], name="finance_pay_employe_88cea5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["budget", "status"], name="finance_pay_budget__0ca194_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["fiscal_year", "status"], name="finance_pay_fiscal__0cdfca_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["executed_date"], name="finance_pay_execute_d40d60_idx"),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(fields=["anomaly_flag"], name="finance_pay_anomaly_606d63_idx"),
        ),
    ]
