# Generated by Django 5.1.4 on 2026-06-13 14:07

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0001_initial"),
        ("tenant", "0002_seed_default_tenant"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="budget",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="financialalert",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="financialentry",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="fiscalyear",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="payment",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="paymentbatch",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="budget",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="financialalert",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="financialentry",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="fiscalyear",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="historicalbudget",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="historicalfinancialalert",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="historicalfinancialentry",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="historicalfiscalyear",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="historicalpayment",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="historicalpaymentbatch",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="paymentbatch",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenant.tenant",
            ),
        ),
    ]
