# Generated by Django 5.1.4 on 2026-06-08 11:05

import apps.loans.models
import django.db.models.deletion
import django.db.models.manager
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0002_alter_employee_managers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalLoan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, help_text="Date de dernière modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                ("workflow_state", models.CharField(db_index=True, max_length=50)),
                ("workflow_updated_at", models.DateTimeField(blank=True, null=True)),
                ("last_transition_at", models.DateTimeField(blank=True, null=True)),
                ("last_transition_reason", models.TextField(blank=True)),
                (
                    "reference",
                    models.CharField(
                        db_index=True, editable=False, max_length=30, verbose_name="Référence"
                    ),
                ),
                (
                    "requested_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Montant demandé (DZD)"
                    ),
                ),
                (
                    "approved_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Montant approuvé (DZD)",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Montant payé (DZD)",
                    ),
                ),
                (
                    "monthly_instalment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Mensualité (DZD)",
                    ),
                ),
                (
                    "instalment_count",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Nombre de mensualités"
                    ),
                ),
                ("reason", models.TextField(verbose_name="Motif du prêt")),
                ("description", models.TextField(blank=True, verbose_name="Observations")),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date de soumission"),
                ),
                (
                    "validated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date de validation"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date de paiement"),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date de rejet"),
                ),
                ("rejection_reason", models.TextField(blank=True, verbose_name="Motif de rejet")),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence de paiement"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="employees.employee",
                        verbose_name="Employé",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "last_transition_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Payé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Prêt",
                "verbose_name_plural": "historical Prêts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Date de dernière modification"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                ("workflow_state", models.CharField(db_index=True, max_length=50)),
                ("workflow_updated_at", models.DateTimeField(blank=True, null=True)),
                ("last_transition_at", models.DateTimeField(blank=True, null=True)),
                ("last_transition_reason", models.TextField(blank=True)),
                (
                    "reference",
                    models.CharField(
                        editable=False, max_length=30, unique=True, verbose_name="Référence"
                    ),
                ),
                (
                    "requested_amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=14, verbose_name="Montant demandé (DZD)"
                    ),
                ),
                (
                    "approved_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Montant approuvé (DZD)",
                    ),
                ),
                (
                    "paid_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Montant payé (DZD)",
                    ),
                ),
                (
                    "monthly_instalment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Mensualité (DZD)",
                    ),
                ),
                (
                    "instalment_count",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Nombre de mensualités"
                    ),
                ),
                ("reason", models.TextField(verbose_name="Motif du prêt")),
                ("description", models.TextField(blank=True, verbose_name="Observations")),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date de soumission"),
                ),
                (
                    "validated_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date de validation"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date de paiement"),
                ),
                (
                    "rejected_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Date de rejet"),
                ),
                ("rejection_reason", models.TextField(blank=True, verbose_name="Motif de rejet")),
                (
                    "payment_reference",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Référence de paiement"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="employees.employee",
                        verbose_name="Employé",
                    ),
                ),
                (
                    "last_transition_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_last_transitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paid_loans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Payé par",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validated_loans",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Validé par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prêt",
                "verbose_name_plural": "Prêts",
                "ordering": ["-created_at"],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalLoanComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, help_text="Date de dernière modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("internal", "Note interne"),
                            ("requester", "Message au demandeur"),
                            ("system", "Message système"),
                        ],
                        default="internal",
                        max_length=15,
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenu")),
                ("workflow_state_at_time", models.CharField(blank=True, max_length=50)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Commentaire",
                "verbose_name_plural": "historical Commentaires",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLoanAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, help_text="Date de dernière modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                ("file", models.TextField(max_length=100, verbose_name="Fichier")),
                ("original_name", models.CharField(max_length=255, verbose_name="Nom original")),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("contract", "Contrat de prêt"),
                            ("identity", "Pièce d'identité"),
                            ("salary_slip", "Bulletin de salaire"),
                            ("bank_details", "RIB bancaire"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, verbose_name="Description"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, verbose_name="Taille (octets)"),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="loans.loan",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Pièce jointe",
                "verbose_name_plural": "historical Pièces jointes",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LoanAttachment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Date de dernière modification"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.loans.models.attachment_upload_path, verbose_name="Fichier"
                    ),
                ),
                ("original_name", models.CharField(max_length=255, verbose_name="Nom original")),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("contract", "Contrat de prêt"),
                            ("identity", "Pièce d'identité"),
                            ("salary_slip", "Bulletin de salaire"),
                            ("bank_details", "RIB bancaire"),
                            ("other", "Autre"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="Type de document",
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=300, verbose_name="Description"),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, verbose_name="Taille (octets)"),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="loans.loan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_loan_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pièce jointe",
                "verbose_name_plural": "Pièces jointes",
                "ordering": ["created_at"],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name="LoanComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Date de dernière modification"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                (
                    "comment_type",
                    models.CharField(
                        choices=[
                            ("internal", "Note interne"),
                            ("requester", "Message au demandeur"),
                            ("system", "Message système"),
                        ],
                        default="internal",
                        max_length=15,
                    ),
                ),
                ("content", models.TextField(verbose_name="Contenu")),
                ("workflow_state_at_time", models.CharField(blank=True, max_length=50)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="loan_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="loans.loan",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Commentaire",
                "verbose_name_plural": "Commentaires",
                "ordering": ["created_at"],
            },
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["reference"], name="loans_loan_referen_8cc656_idx"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["workflow_state"], name="loans_loan_workflo_1d751d_idx"),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(
                fields=["employee", "workflow_state"], name="loans_loan_employe_bc2478_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loan",
            index=models.Index(fields=["submitted_at"], name="loans_loan_submitt_81111b_idx"),
        ),
    ]
