# Generated by Django 5.1.4 on 2026-06-13 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0001_initial"),
        ("tenant", "0002_seed_default_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalloan",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="historicalloanattachment",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="historicalloancomment",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="loanattachment",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="loancomment",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenant.tenant",
            ),
        ),
    ]
