# Generated by Django 5.1.4 on 2026-05-19 21:11

import apps.employees.models
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Date de dernière modification"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                (
                    "matricule",
                    models.CharField(max_length=20, unique=True, verbose_name="Matricule"),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "first_name_ar",
                    models.CharField(blank=True, max_length=100, verbose_name="Prénom (arabe)"),
                ),
                (
                    "last_name_ar",
                    models.CharField(blank=True, max_length=100, verbose_name="Nom (arabe)"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")],
                        max_length=1,
                        verbose_name="Genre",
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="Date de naissance")),
                (
                    "place_of_birth",
                    models.CharField(blank=True, max_length=100, verbose_name="Lieu de naissance"),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("single", "Célibataire"),
                            ("married", "Marié(e)"),
                            ("divorced", "Divorcé(e)"),
                            ("widowed", "Veuf/Veuve"),
                        ],
                        default="single",
                        max_length=10,
                        verbose_name="Situation familiale",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        default="Algérienne", max_length=50, verbose_name="Nationalité"
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True, max_length=20, null=True, unique=True, verbose_name="NNI / CIN"
                    ),
                ),
                (
                    "national_id_expiry",
                    models.DateField(blank=True, null=True, verbose_name="Expiration CIN"),
                ),
                (
                    "social_security_number",
                    models.CharField(blank=True, max_length=30, verbose_name="N° SS"),
                ),
                ("tax_id", models.CharField(blank=True, max_length=20, verbose_name="NIF")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="Téléphone")),
                (
                    "phone_secondary",
                    models.CharField(blank=True, max_length=20, verbose_name="Tél. secondaire"),
                ),
                (
                    "email_personal",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email personnel"),
                ),
                (
                    "email_professional",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email professionnel"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adresse")),
                ("city", models.CharField(blank=True, max_length=100, verbose_name="Ville")),
                ("wilaya", models.CharField(blank=True, max_length=100, verbose_name="Wilaya")),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.employees.models.employee_photo_path,
                        verbose_name="Photo",
                    ),
                ),
                ("job_title", models.CharField(max_length=150, verbose_name="Intitulé du poste")),
                ("grade", models.CharField(blank=True, max_length=100, verbose_name="Grade")),
                (
                    "grade_level",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Niveau grade"
                    ),
                ),
                (
                    "category",
                    models.CharField(blank=True, max_length=50, verbose_name="Catégorie CSP"),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("cdi", "CDI"),
                            ("cdd", "CDD"),
                            ("stage", "Stagiaire"),
                            ("part_time", "Temps partiel"),
                            ("consultant", "Consultant"),
                        ],
                        default="cdi",
                        max_length=20,
                        verbose_name="Type de contrat",
                    ),
                ),
                ("date_hired", models.DateField(verbose_name="Date d'embauche")),
                (
                    "date_end",
                    models.DateField(blank=True, null=True, verbose_name="Date fin contrat"),
                ),
                (
                    "date_retired",
                    models.DateField(blank=True, null=True, verbose_name="Date retraite"),
                ),
                (
                    "date_promoted",
                    models.DateField(blank=True, null=True, verbose_name="Dernière promotion"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("inactive", "Inactif"),
                            ("retired", "Retraité"),
                            ("suspended", "Suspendu"),
                            ("deceased", "Décédé"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "base_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Salaire de base (DZD)",
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(blank=True, max_length=50, verbose_name="RIB/CCP"),
                ),
                (
                    "education_level",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Niveau de formation"
                    ),
                ),
                (
                    "education_field",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Domaine de formation"
                    ),
                ),
                (
                    "competencies",
                    models.JSONField(blank=True, default=list, verbose_name="Compétences"),
                ),
                (
                    "scoring_profile",
                    models.JSONField(blank=True, default=dict, verbose_name="Profil scoring AI"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Métadonnées"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes internes")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employees",
                        to="departments.department",
                        verbose_name="Département",
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subordinates",
                        to="employees.employee",
                        verbose_name="Supérieur hiérarchique",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Employé",
                "verbose_name_plural": "Employés",
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalEmployee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, help_text="Date de dernière modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                (
                    "matricule",
                    models.CharField(db_index=True, max_length=20, verbose_name="Matricule"),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "first_name_ar",
                    models.CharField(blank=True, max_length=100, verbose_name="Prénom (arabe)"),
                ),
                (
                    "last_name_ar",
                    models.CharField(blank=True, max_length=100, verbose_name="Nom (arabe)"),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Masculin"), ("F", "Féminin")],
                        max_length=1,
                        verbose_name="Genre",
                    ),
                ),
                ("date_of_birth", models.DateField(verbose_name="Date de naissance")),
                (
                    "place_of_birth",
                    models.CharField(blank=True, max_length=100, verbose_name="Lieu de naissance"),
                ),
                (
                    "marital_status",
                    models.CharField(
                        choices=[
                            ("single", "Célibataire"),
                            ("married", "Marié(e)"),
                            ("divorced", "Divorcé(e)"),
                            ("widowed", "Veuf/Veuve"),
                        ],
                        default="single",
                        max_length=10,
                        verbose_name="Situation familiale",
                    ),
                ),
                (
                    "nationality",
                    models.CharField(
                        default="Algérienne", max_length=50, verbose_name="Nationalité"
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=20,
                        null=True,
                        verbose_name="NNI / CIN",
                    ),
                ),
                (
                    "national_id_expiry",
                    models.DateField(blank=True, null=True, verbose_name="Expiration CIN"),
                ),
                (
                    "social_security_number",
                    models.CharField(blank=True, max_length=30, verbose_name="N° SS"),
                ),
                ("tax_id", models.CharField(blank=True, max_length=20, verbose_name="NIF")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="Téléphone")),
                (
                    "phone_secondary",
                    models.CharField(blank=True, max_length=20, verbose_name="Tél. secondaire"),
                ),
                (
                    "email_personal",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email personnel"),
                ),
                (
                    "email_professional",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Email professionnel"
                    ),
                ),
                ("address", models.TextField(blank=True, verbose_name="Adresse")),
                ("city", models.CharField(blank=True, max_length=100, verbose_name="Ville")),
                ("wilaya", models.CharField(blank=True, max_length=100, verbose_name="Wilaya")),
                (
                    "photo",
                    models.TextField(blank=True, max_length=100, null=True, verbose_name="Photo"),
                ),
                ("job_title", models.CharField(max_length=150, verbose_name="Intitulé du poste")),
                ("grade", models.CharField(blank=True, max_length=100, verbose_name="Grade")),
                (
                    "grade_level",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Niveau grade"
                    ),
                ),
                (
                    "category",
                    models.CharField(blank=True, max_length=50, verbose_name="Catégorie CSP"),
                ),
                (
                    "contract_type",
                    models.CharField(
                        choices=[
                            ("cdi", "CDI"),
                            ("cdd", "CDD"),
                            ("stage", "Stagiaire"),
                            ("part_time", "Temps partiel"),
                            ("consultant", "Consultant"),
                        ],
                        default="cdi",
                        max_length=20,
                        verbose_name="Type de contrat",
                    ),
                ),
                ("date_hired", models.DateField(verbose_name="Date d'embauche")),
                (
                    "date_end",
                    models.DateField(blank=True, null=True, verbose_name="Date fin contrat"),
                ),
                (
                    "date_retired",
                    models.DateField(blank=True, null=True, verbose_name="Date retraite"),
                ),
                (
                    "date_promoted",
                    models.DateField(blank=True, null=True, verbose_name="Dernière promotion"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Actif"),
                            ("inactive", "Inactif"),
                            ("retired", "Retraité"),
                            ("suspended", "Suspendu"),
                            ("deceased", "Décédé"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "base_salary",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        verbose_name="Salaire de base (DZD)",
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(blank=True, max_length=50, verbose_name="RIB/CCP"),
                ),
                (
                    "education_level",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Niveau de formation"
                    ),
                ),
                (
                    "education_field",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Domaine de formation"
                    ),
                ),
                (
                    "competencies",
                    models.JSONField(blank=True, default=list, verbose_name="Compétences"),
                ),
                (
                    "scoring_profile",
                    models.JSONField(blank=True, default=dict, verbose_name="Profil scoring AI"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Métadonnées"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes internes")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="departments.department",
                        verbose_name="Département",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="employees.employee",
                        verbose_name="Supérieur hiérarchique",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Dernier utilisateur modificateur",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Employé",
                "verbose_name_plural": "historical Employés",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["matricule"], name="employees_e_matricu_4b5279_idx"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["status"], name="employees_e_status_61c2f6_idx"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["department"], name="employees_e_departm_99b42d_idx"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["last_name", "first_name"], name="employees_e_last_na_99a4c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["date_hired"], name="employees_e_date_hi_6817a8_idx"),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(fields=["grade_level"], name="employees_e_grade_l_65c9c8_idx"),
        ),
    ]
