# Generated by Django 6.0.5 on 2026-06-06 15:42

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employee',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
