# Generated by django 5.1.4
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
        ("employees", "0003_employee_tenant_historicalemployee_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="bureau",
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="organization.Bureau",
                verbose_name="Bureau",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="function",
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="organization.Function",
                verbose_name="Fonction",
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="grade_ref",
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="organization.Grade",
                verbose_name="Grade (référentiel)",
            ),
        ),
    ]
