# Generated by Django 5.1.4 on 2026-05-19 21:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkflowLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("content_type_name", models.CharField(db_index=True, max_length=100)),
                ("object_id", models.CharField(db_index=True, max_length=255)),
                ("from_state", models.CharField(max_length=50)),
                ("to_state", models.CharField(db_index=True, max_length=50)),
                ("transition_name", models.CharField(max_length=100)),
                ("actor_email", models.EmailField(blank=True, max_length=254)),
                ("actor_role", models.CharField(blank=True, max_length=30)),
                ("reason", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("is_reversal", models.BooleanField(default=False)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Faible"),
                            ("MEDIUM", "Moyen"),
                            ("HIGH", "Élevé"),
                            ("CRITICAL", "Critique"),
                        ],
                        default="LOW",
                        max_length=10,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workflow_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Log workflow",
                "verbose_name_plural": "Logs workflow",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["content_type_name", "object_id"],
                        name="workflow_wo_content_dfc5a1_idx",
                    ),
                    models.Index(
                        fields=["to_state", "-timestamp"], name="workflow_wo_to_stat_6b79c0_idx"
                    ),
                    models.Index(
                        fields=["is_reversal", "-timestamp"], name="workflow_wo_is_reve_1c5e15_idx"
                    ),
                ],
            },
        ),
    ]
