# Generated by Django 6.0.5 on 2026-06-13 13:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_add_performance_indexes'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_label', models.CharField(db_index=True, max_length=100)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('state_id', models.CharField(max_length=50)),
                ('label_fr', models.CharField(max_length=100)),
                ('label_ar', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(default='#6B7280', max_length=7)),
                ('is_initial', models.BooleanField(default=False)),
                ('is_final', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'État de workflow',
                'verbose_name_plural': 'États de workflow',
                'ordering': ['app_label', 'model_name', 'display_order'],
                'unique_together': {('app_label', 'model_name', 'state_id')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_label', models.CharField(db_index=True, max_length=100)),
                ('model_name', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('label_fr', models.CharField(max_length=100)),
                ('label_ar', models.CharField(blank=True, max_length=100)),
                ('requires_reason', models.BooleanField(default=False)),
                ('is_reversal', models.BooleanField(default=False)),
                ('severity', models.CharField(choices=[('LOW', 'Faible'), ('MEDIUM', 'Moyen'), ('HIGH', 'Élevé'), ('CRITICAL', 'Critique')], default='LOW', max_length=10)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_transitions', to='workflow.workflowstate')),
                ('to_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='workflow.workflowstate')),
            ],
            options={
                'verbose_name': 'Transition de workflow',
                'verbose_name_plural': 'Transitions de workflow',
                'ordering': ['app_label', 'model_name', 'display_order'],
                'unique_together': {('app_label', 'model_name', 'from_state', 'to_state')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowTransitionRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workflow_transition_roles', to='administration.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workflow_transition_roles', to='administration.role')),
                ('transition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_roles', to='workflow.workflowtransition')),
            ],
            options={
                'verbose_name': 'Rôle autorisé pour transition',
                'verbose_name_plural': 'Rôles autorisés pour transitions',
                'unique_together': {('transition', 'role')},
            },
        ),
    ]
