# Generated by Django 5.1.4 on 2026-06-10 09:13

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0001_initial_conventions"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="convention",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="conventionalert",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="conventiondocument",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="partner",
            managers=[
                ("all_objects", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="historicalpartner",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("medical_analysis_lab", "Medical Analysis Laboratory"),
                    ("medical_center", "Medical Center"),
                    ("medical_imaging_center", "Medical Imaging Center"),
                ],
                max_length=30,
                verbose_name="Catégorie partenaire",
            ),
        ),
        migrations.AddField(
            model_name="historicalpartner",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="historicalpartner",
            name="gps_coordinates",
            field=models.CharField(blank=True, max_length=100, verbose_name="Coordonnées GPS"),
        ),
        migrations.AddField(
            model_name="partner",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("medical_analysis_lab", "Medical Analysis Laboratory"),
                    ("medical_center", "Medical Center"),
                    ("medical_imaging_center", "Medical Imaging Center"),
                ],
                max_length=30,
                verbose_name="Catégorie partenaire",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AddField(
            model_name="partner",
            name="gps_coordinates",
            field=models.CharField(blank=True, max_length=100, verbose_name="Coordonnées GPS"),
        ),
    ]
