# Generated by Django 5.1.4 on 2026-06-11 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0002_alter_convention_managers_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpartner",
            name="pdf_template",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Template par défaut"),
                    ("imaging_center", "Centre d'imagerie médicale"),
                    ("analysis_lab", "Laboratoire d'analyses médicales"),
                    ("medical_center", "Centre médical"),
                ],
                default="default",
                help_text="Template de prise en charge PDF spécifique au partenaire",
                max_length=50,
                verbose_name="Template PDF",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="pdf_template",
            field=models.CharField(
                blank=True,
                choices=[
                    ("default", "Template par défaut"),
                    ("imaging_center", "Centre d'imagerie médicale"),
                    ("analysis_lab", "Laboratoire d'analyses médicales"),
                    ("medical_center", "Centre médical"),
                ],
                default="default",
                help_text="Template de prise en charge PDF spécifique au partenaire",
                max_length=50,
                verbose_name="Template PDF",
            ),
        ),
    ]
