# Generated by Django 5.1.4 on 2026-06-13 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conventions", "0003_historicalpartner_pdf_template_partner_pdf_template"),
        ("tenant", "0002_seed_default_tenant"),
    ]

    operations = [
        migrations.AddField(
            model_name="convention",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="conventionalert",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="conventiondocument",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="historicalconvention",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="historicalconventionalert",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="historicalconventiondocument",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="historicalpartner",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tenant.tenant",
            ),
        ),
        migrations.AddField(
            model_name="partner",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                help_text="Organisme de rattachement (multi-tenant)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tenant.tenant",
            ),
        ),
    ]
