# Generated by Django 5.1.4 on 2026-05-19 21:11

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalDepartment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, help_text="Date de dernière modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Code unique : RH, FIN, TECH, etc.",
                        max_length=20,
                        verbose_name="Code département",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nom du département")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "budget_annual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Pour analytics budgétaires futurs",
                        max_digits=15,
                        null=True,
                        verbose_name="Budget annuel (DZD)",
                    ),
                ),
                (
                    "cost_center",
                    models.CharField(blank=True, max_length=50, verbose_name="Centre de coût"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="Localisation"),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Département",
                "verbose_name_plural": "historical Départements",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Date de dernière modification"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Code unique : RH, FIN, TECH, etc.",
                        max_length=20,
                        unique=True,
                        verbose_name="Code département",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Nom du département")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "budget_annual",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Pour analytics budgétaires futurs",
                        max_digits=15,
                        null=True,
                        verbose_name="Budget annuel (DZD)",
                    ),
                ),
                (
                    "cost_center",
                    models.CharField(blank=True, max_length=50, verbose_name="Centre de coût"),
                ),
                (
                    "location",
                    models.CharField(blank=True, max_length=200, verbose_name="Localisation"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Département",
                "verbose_name_plural": "Départements",
                "ordering": ["code"],
            },
        ),
    ]
