# Generated by Django 5.1.4 on 2026-05-19 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("departments", "0001_initial"),
        ("employees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managed_departments",
                to="employees.employee",
                verbose_name="Responsable",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Pour la hiérarchie organisationnelle",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="departments.department",
                verbose_name="Département parent",
            ),
        ),
        migrations.AddField(
            model_name="department",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Dernier utilisateur modificateur",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaldepartment",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Utilisateur créateur",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaldepartment",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Utilisateur ayant supprimé",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaldepartment",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaldepartment",
            name="manager",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="employees.employee",
                verbose_name="Responsable",
            ),
        ),
        migrations.AddField(
            model_name="historicaldepartment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Pour la hiérarchie organisationnelle",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="departments.department",
                verbose_name="Département parent",
            ),
        ),
        migrations.AddField(
            model_name="historicaldepartment",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Dernier utilisateur modificateur",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["code"], name="departments_code_35a421_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["is_active"], name="departments_is_acti_51d68f_idx"),
        ),
    ]
