# Generated by Django 5.1.4 on 2026-05-19 23:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIFeature",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("feature_name", models.CharField(db_index=True, max_length=100)),
                (
                    "feature_type",
                    models.CharField(
                        choices=[
                            ("numeric", "Numérique"),
                            ("categorical", "Catégorielle"),
                            ("boolean", "Booléenne"),
                            ("timestamp", "Horodatage"),
                            ("text", "Texte"),
                            ("embedding", "Embedding"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type d'entité (Benefit, Employee, etc.)",
                        max_length=50,
                    ),
                ),
                ("entity_id", models.CharField(db_index=True, max_length=255)),
                ("value_numeric", models.FloatField(blank=True, null=True)),
                ("value_text", models.TextField(blank=True)),
                ("value_bool", models.BooleanField(null=True)),
                ("value_json", models.JSONField(blank=True, default=dict)),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="Source de la feature (pipeline, model)",
                        max_length=100,
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "ttl_seconds",
                    models.PositiveIntegerField(
                        blank=True, help_text="Durée de validité en secondes", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature IA",
                "verbose_name_plural": "Features IA",
                "indexes": [
                    models.Index(
                        fields=["feature_name", "entity_type", "entity_id"],
                        name="ai_aifeatur_feature_8e7e75_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id", "feature_name"],
                        name="ai_aifeatur_entity__4500d2_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIModelRegistry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=20)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("anomaly", "Détection d'anomalies"),
                            ("scoring", "Scoring de demandes"),
                            ("forecast", "Prévisions budgétaires"),
                            ("recommendation", "Recommandations"),
                            ("behavior", "Analyse comportementale"),
                            ("assistant", "Assistant IA"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("dev", "Développement"),
                            ("staging", "Test"),
                            ("production", "Production"),
                            ("deprecated", "Déprécié"),
                            ("archived", "Archivé"),
                        ],
                        default="dev",
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "algorithm",
                    models.CharField(blank=True, help_text="Algorithme utilisé", max_length=100),
                ),
                (
                    "features_used",
                    models.JSONField(
                        blank=True, default=list, help_text="Liste des features utilisées"
                    ),
                ),
                ("training_date", models.DateTimeField(blank=True, null=True)),
                ("training_duration_s", models.FloatField(blank=True, null=True)),
                ("training_data_count", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "metrics",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Métriques d'évaluation (accuracy, precision, recall, f1, mae, rmse)",
                    ),
                ),
                ("hyperparams", models.JSONField(blank=True, default=dict)),
                (
                    "artifact_path",
                    models.CharField(
                        blank=True, help_text="Chemin vers l'artefact du modèle", max_length=500
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trained_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Registre modèle IA",
                "verbose_name_plural": "Registre modèles IA",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIAnomaly",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "detection_method",
                    models.CharField(
                        help_text="Méthode ayant détecté (zscore, iqr, moving_avg, seasonal, ensemble)",
                        max_length=50,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Faible"),
                            ("medium", "Moyen"),
                            ("high", "Élevé"),
                            ("critical", "Critique"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Nouveau"),
                            ("confirmed", "Confirmé"),
                            ("false_positive", "Faux positif"),
                            ("investigating", "En investigation"),
                            ("resolved", "Résolu"),
                        ],
                        default="new",
                        max_length=15,
                    ),
                ),
                ("target_type", models.CharField(help_text="Type d'objet concerné", max_length=50)),
                ("target_id", models.CharField(max_length=255)),
                ("target_repr", models.CharField(blank=True, max_length=500)),
                (
                    "metric_name",
                    models.CharField(
                        blank=True, help_text="Nom de la métrique anormale", max_length=100
                    ),
                ),
                ("expected_value", models.FloatField(blank=True, null=True)),
                ("actual_value", models.FloatField(blank=True, null=True)),
                ("deviation", models.FloatField(blank=True, help_text="Écart absolu", null=True)),
                ("deviation_pct", models.FloatField(blank=True, help_text="Écart en %", null=True)),
                ("zscore", models.FloatField(blank=True, null=True)),
                (
                    "context",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Données contextuelles au moment de la détection",
                    ),
                ),
                ("explanation", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai.aimodelregistry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anomalie IA",
                "verbose_name_plural": "Anomalies IA",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIPrediction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "prediction_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type de prédiction (trend, budget, scoring)",
                        max_length=30,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        help_text="Type d'objet prédit (Benefit, Budget, etc.)",
                        max_length=50,
                    ),
                ),
                ("target_id", models.CharField(blank=True, max_length=255)),
                ("input_data", models.JSONField(blank=True, default=dict)),
                ("output_data", models.JSONField(blank=True, default=dict)),
                (
                    "confidence",
                    models.FloatField(blank=True, help_text="Indice de confiance 0-1", null=True),
                ),
                ("features_used", models.JSONField(blank=True, default=list)),
                (
                    "explanation",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Explication de la prédiction (SHAP-like)",
                    ),
                ),
                ("execution_time_ms", models.PositiveIntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Invalider manuellement les prédictions obsolètes"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai.aimodelregistry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Prédiction IA",
                "verbose_name_plural": "Prédictions IA",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIRecommendation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        db_index=True,
                        help_text="Domaine (finance, conventions, benefits, hr)",
                        max_length=30,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Basse"),
                            ("medium", "Moyenne"),
                            ("high", "Haute"),
                            ("critical", "Critique"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("detail", models.TextField(blank=True)),
                (
                    "action_url",
                    models.CharField(blank=True, help_text="Lien vers l'action", max_length=500),
                ),
                ("action_label", models.CharField(blank=True, max_length=100)),
                (
                    "source_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Données ayant généré la recommandation"
                    ),
                ),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "feedback",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("helpful", "Utile"),
                            ("not_helpful", "Pas utile"),
                            ("applied", "Appliquée"),
                            ("dismissed", "Ignorée"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("feedback_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="La recommandation expire après cette date", null=True
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "feedback_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai.aimodelregistry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recommandation IA",
                "verbose_name_plural": "Recommandations IA",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIScore",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "score_type",
                    models.CharField(
                        db_index=True,
                        help_text="Type de score (demand, risk, priority, fraud)",
                        max_length=30,
                    ),
                ),
                ("target_type", models.CharField(max_length=50)),
                ("target_id", models.CharField(max_length=255)),
                ("target_repr", models.CharField(blank=True, max_length=500)),
                ("score", models.FloatField(help_text="Score 0-100")),
                (
                    "confidence",
                    models.FloatField(blank=True, help_text="Confiance du modèle 0-1", null=True),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True, default=dict, help_text="Features utilisées pour le score"
                    ),
                ),
                (
                    "feature_importance",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Importance de chaque feature (SHAP-like)",
                    ),
                ),
                (
                    "explanation",
                    models.TextField(blank=True, help_text="Explication lisible du score"),
                ),
                (
                    "decision_boundary",
                    models.FloatField(blank=True, help_text="Seuil de décision", null=True),
                ),
                (
                    "recommendation",
                    models.CharField(blank=True, help_text="Action recommandée", max_length=50),
                ),
                ("ai_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, help_text="Date d'expiration du score", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ai.aimodelregistry",
                    ),
                ),
            ],
            options={
                "verbose_name": "Score IA",
                "verbose_name_plural": "Scores IA",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("user_email", models.EmailField(blank=True, max_length=254)),
                ("user_role", models.CharField(blank=True, max_length=30)),
                ("session_id", models.CharField(blank=True, db_index=True, max_length=100)),
                (
                    "event_category",
                    models.CharField(
                        choices=[
                            ("navigation", "Navigation"),
                            ("action", "Action utilisateur"),
                            ("workflow", "Transition workflow"),
                            ("search", "Recherche"),
                            ("export", "Export"),
                            ("login", "Connexion"),
                            ("api_call", "Appel API"),
                        ],
                        max_length=20,
                    ),
                ),
                ("event_name", models.CharField(db_index=True, max_length=100)),
                ("target_type", models.CharField(blank=True, max_length=50)),
                ("target_id", models.CharField(blank=True, max_length=255)),
                (
                    "properties",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Propriétés contextuelles de l'événement",
                    ),
                ),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Événement IA",
                "verbose_name_plural": "Événements IA",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"], name="ai_aievent_user_id_a579ee_idx"
                    ),
                    models.Index(
                        fields=["event_category", "event_name"],
                        name="ai_aievent_event_c_819c9e_idx",
                    ),
                    models.Index(fields=["session_id"], name="ai_aievent_session_432046_idx"),
                    models.Index(fields=["-timestamp"], name="ai_aievent_timesta_c9bac7_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="AIFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        help_text="Type (prediction, anomaly, score, recommendation)", max_length=20
                    ),
                ),
                ("target_type", models.CharField(max_length=50)),
                ("target_id", models.CharField(max_length=255)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Pas du tout pertinent"),
                            (2, "Peu pertinent"),
                            (3, "Neutre"),
                            (4, "Pertinent"),
                            (5, "Très pertinent"),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                (
                    "expected_value",
                    models.FloatField(
                        blank=True, help_text="Valeur attendue par l'utilisateur", null=True
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Feedback IA",
                "verbose_name_plural": "Feedbacks IA",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["feedback_type", "-created_at"],
                        name="ai_aifeedba_feedbac_dc5e3f_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"], name="ai_aifeedba_user_id_49e8d7_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="aimodelregistry",
            index=models.Index(
                fields=["task_type", "status"], name="ai_aimodelr_task_ty_e372cc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aimodelregistry",
            index=models.Index(fields=["name", "version"], name="ai_aimodelr_name_6e1a3a_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="aimodelregistry",
            unique_together={("name", "version")},
        ),
        migrations.AddIndex(
            model_name="aianomaly",
            index=models.Index(
                fields=["severity", "status"], name="ai_aianomal_severit_b337e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aianomaly",
            index=models.Index(
                fields=["target_type", "target_id"], name="ai_aianomal_target__6dff95_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aianomaly",
            index=models.Index(fields=["detection_method"], name="ai_aianomal_detecti_29b316_idx"),
        ),
        migrations.AddIndex(
            model_name="aiprediction",
            index=models.Index(
                fields=["prediction_type", "-created_at"], name="ai_aipredic_predict_118d1c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiprediction",
            index=models.Index(
                fields=["target_type", "target_id"], name="ai_aipredic_target__3a9cc0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airecommendation",
            index=models.Index(fields=["domain", "priority"], name="ai_airecomm_domain_163776_idx"),
        ),
        migrations.AddIndex(
            model_name="airecommendation",
            index=models.Index(fields=["feedback"], name="ai_airecomm_feedbac_32e560_idx"),
        ),
        migrations.AddIndex(
            model_name="aiscore",
            index=models.Index(
                fields=["score_type", "-created_at"], name="ai_aiscore_score_t_8ff243_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiscore",
            index=models.Index(
                fields=["target_type", "target_id"], name="ai_aiscore_target__f10d96_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aiscore",
            index=models.Index(fields=["score"], name="ai_aiscore_score_6df3a8_idx"),
        ),
    ]
