# Generated by Django 5.1.4 on 2026-05-19 21:11

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalBeneficiary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(blank=True, editable=False, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        blank=True, editable=False, help_text="Date de dernière modification"
                    ),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                ("first_name_ar", models.CharField(blank=True, max_length=100)),
                ("last_name_ar", models.CharField(blank=True, max_length=100)),
                (
                    "gender",
                    models.CharField(choices=[("M", "Masculin"), ("F", "Féminin")], max_length=1),
                ),
                ("date_of_birth", models.DateField(verbose_name="Date de naissance")),
                ("national_id", models.CharField(blank=True, max_length=20, verbose_name="NNI")),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("spouse", "Conjoint(e)"),
                            ("child", "Enfant"),
                            ("parent", "Parent"),
                            ("sibling", "Frère/Sœur"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Lien de parenté",
                    ),
                ),
                ("is_eligible", models.BooleanField(default=True, verbose_name="Éligible")),
                ("ineligibility_reason", models.CharField(blank=True, max_length=300)),
                ("is_student", models.BooleanField(default=False, verbose_name="Étudiant(e)")),
                ("is_handicapped", models.BooleanField(default=False, verbose_name="Handicapé(e)")),
                ("school_name", models.CharField(blank=True, max_length=200)),
                ("school_year", models.CharField(blank=True, max_length=20)),
                ("spouse_is_employed", models.BooleanField(blank=True, null=True)),
                ("spouse_employer", models.CharField(blank=True, max_length=200)),
                ("birth_certificate_uploaded", models.BooleanField(default=False)),
                ("marriage_certificate_uploaded", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.TextField(null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")], max_length=1
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Ayant droit",
                "verbose_name_plural": "historical Ayants droit",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Beneficiary",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Identifiant unique universel",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, help_text="Date de création"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, help_text="Date de dernière modification"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False, help_text="Suppression logique (soft delete)"
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True, help_text="Date de suppression logique", null=True
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Prénom")),
                ("last_name", models.CharField(max_length=100, verbose_name="Nom")),
                ("first_name_ar", models.CharField(blank=True, max_length=100)),
                ("last_name_ar", models.CharField(blank=True, max_length=100)),
                (
                    "gender",
                    models.CharField(choices=[("M", "Masculin"), ("F", "Féminin")], max_length=1),
                ),
                ("date_of_birth", models.DateField(verbose_name="Date de naissance")),
                ("national_id", models.CharField(blank=True, max_length=20, verbose_name="NNI")),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("spouse", "Conjoint(e)"),
                            ("child", "Enfant"),
                            ("parent", "Parent"),
                            ("sibling", "Frère/Sœur"),
                            ("other", "Autre"),
                        ],
                        max_length=20,
                        verbose_name="Lien de parenté",
                    ),
                ),
                ("is_eligible", models.BooleanField(default=True, verbose_name="Éligible")),
                ("ineligibility_reason", models.CharField(blank=True, max_length=300)),
                ("is_student", models.BooleanField(default=False, verbose_name="Étudiant(e)")),
                ("is_handicapped", models.BooleanField(default=False, verbose_name="Handicapé(e)")),
                ("school_name", models.CharField(blank=True, max_length=200)),
                ("school_year", models.CharField(blank=True, max_length=20)),
                ("spouse_is_employed", models.BooleanField(blank=True, null=True)),
                ("spouse_employer", models.CharField(blank=True, max_length=200)),
                ("birth_certificate_uploaded", models.BooleanField(default=False)),
                ("marriage_certificate_uploaded", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur créateur",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur ayant supprimé",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ayant droit",
                "verbose_name_plural": "Ayants droit",
                "ordering": ["relationship", "last_name"],
            },
        ),
    ]
