# Generated by Django 5.1.4 on 2026-05-19 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("beneficiaries", "0001_initial"),
        ("employees", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiary",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="beneficiaries",
                to="employees.employee",
                verbose_name="Employé",
            ),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Dernier utilisateur modificateur",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_updated",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalbeneficiary",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Utilisateur créateur",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalbeneficiary",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Utilisateur ayant supprimé",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalbeneficiary",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="employees.employee",
                verbose_name="Employé",
            ),
        ),
        migrations.AddField(
            model_name="historicalbeneficiary",
            name="history_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicalbeneficiary",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Dernier utilisateur modificateur",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="beneficiary",
            index=models.Index(fields=["employee"], name="beneficiari_employe_d125a4_idx"),
        ),
        migrations.AddIndex(
            model_name="beneficiary",
            index=models.Index(fields=["relationship"], name="beneficiari_relatio_39e0a9_idx"),
        ),
        migrations.AddIndex(
            model_name="beneficiary",
            index=models.Index(fields=["is_eligible"], name="beneficiari_is_elig_e990c0_idx"),
        ),
    ]
