# Generated by Django 5.1.4 on 2026-06-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("beneficiaries", "0003_alter_beneficiary_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="beneficiary",
            name="address",
            field=models.TextField(blank=True, verbose_name="Adresse"),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Téléphone"),
        ),
        migrations.AddField(
            model_name="beneficiary",
            name="social_security_number",
            field=models.CharField(blank=True, max_length=30, verbose_name="N° SS"),
        ),
        migrations.AddField(
            model_name="historicalbeneficiary",
            name="address",
            field=models.TextField(blank=True, verbose_name="Adresse"),
        ),
        migrations.AddField(
            model_name="historicalbeneficiary",
            name="phone",
            field=models.CharField(blank=True, max_length=20, verbose_name="Téléphone"),
        ),
        migrations.AddField(
            model_name="historicalbeneficiary",
            name="social_security_number",
            field=models.CharField(blank=True, max_length=30, verbose_name="N° SS"),
        ),
    ]
