# Generated by Django 5.1.4 on 2026-05-19 21:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email dupliqué pour conservation après suppression user",
                        max_length=254,
                    ),
                ),
                (
                    "user_role",
                    models.CharField(
                        blank=True, help_text="Rôle au moment de l'action", max_length=20
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, help_text="Adresse IP de l'utilisateur", null=True
                    ),
                ),
                ("user_agent", models.TextField(blank=True, help_text="User-Agent du navigateur")),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Création"),
                            ("UPDATE", "Modification"),
                            ("DELETE", "Suppression"),
                            ("VIEW", "Consultation"),
                            ("LOGIN", "Connexion"),
                            ("LOGOUT", "Déconnexion"),
                            ("LOGIN_FAILED", "Tentative échouée"),
                            ("EXPORT", "Export"),
                            ("APPROVE", "Validation"),
                            ("REJECT", "Rejet"),
                            ("SUBMIT", "Soumission"),
                            ("PAY", "Paiement"),
                            ("WORKFLOW_TRANSITION", "Transition workflow"),
                        ],
                        help_text="Type d'action effectuée",
                        max_length=30,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("LOW", "Faible"),
                            ("MEDIUM", "Moyen"),
                            ("HIGH", "Élevé"),
                            ("CRITICAL", "Critique"),
                        ],
                        default="LOW",
                        help_text="Niveau de criticité",
                        max_length=10,
                    ),
                ),
                (
                    "content_type_name",
                    models.CharField(
                        blank=True,
                        help_text="Nom du modèle concerné (ex: benefits.Benefit)",
                        max_length=100,
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True, help_text="ID de l'objet concerné", max_length=255
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(
                        blank=True, help_text="Représentation textuelle de l'objet", max_length=500
                    ),
                ),
                (
                    "before_data",
                    models.JSONField(
                        blank=True, help_text="État avant modification (pour diff et ML)", null=True
                    ),
                ),
                (
                    "after_data",
                    models.JSONField(
                        blank=True, help_text="État après modification (pour diff et ML)", null=True
                    ),
                ),
                (
                    "changed_fields",
                    models.JSONField(blank=True, help_text="Liste des champs modifiés", null=True),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True, default=dict, help_text="Données contextuelles supplémentaires"
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True,
                        help_text="ID unique de la requête HTTP (pour corrélation logs)",
                        max_length=100,
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(blank=True, help_text="Endpoint API appelé", max_length=500),
                ),
                ("http_method", models.CharField(blank=True, max_length=10)),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, help_text="Horodatage exact de l'action"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Utilisateur ayant effectué l'action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Journal d'audit",
                "verbose_name_plural": "Journal d'audit",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "-timestamp"], name="audit_audit_user_id_ea8c9f_idx"
                    ),
                    models.Index(
                        fields=["action", "-timestamp"], name="audit_audit_action_e33994_idx"
                    ),
                    models.Index(
                        fields=["content_type_name", "object_id"],
                        name="audit_audit_content_877c4a_idx",
                    ),
                    models.Index(
                        fields=["severity", "-timestamp"], name="audit_audit_severit_34f2e8_idx"
                    ),
                    models.Index(fields=["-timestamp"], name="audit_audit_timesta_901180_idx"),
                ],
            },
        ),
    ]
