# Generated by Django 5.1.4 on 2026-05-19 23:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("CREATE", "Création"),
                    ("UPDATE", "Modification"),
                    ("DELETE", "Suppression"),
                    ("VIEW", "Consultation"),
                    ("LOGIN", "Connexion"),
                    ("LOGOUT", "Déconnexion"),
                    ("LOGIN_FAILED", "Tentative échouée"),
                    ("EXPORT", "Export"),
                    ("APPROVE", "Validation"),
                    ("REJECT", "Rejet"),
                    ("SUBMIT", "Soumission"),
                    ("PAY", "Paiement"),
                    ("WORKFLOW_TRANSITION", "Transition workflow"),
                    ("VALIDATE", "Validation"),
                    ("CERTIFY", "Certification"),
                    ("SIGN", "Signature"),
                    ("AUDIT_ACCESS", "Consultation audit"),
                    ("ARCHIVE", "Archivage"),
                    ("RESTORE", "Restauration"),
                    ("IMPERSONATE", "Impersonnalisation"),
                    ("CONFIG_CHANGE", "Modification configuration"),
                    ("BULK_OPERATION", "Opération en masse"),
                ],
                help_text="Type d'action effectuée",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ValidationTrace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "validation_type",
                    models.CharField(
                        choices=[
                            ("APPROVE", "Approbation"),
                            ("REJECT", "Rejet"),
                            ("SIGN", "Signature"),
                            ("CERTIFY", "Certification"),
                            ("VALIDATE", "Validation"),
                            ("AUDIT", "Vérification"),
                            ("REVIEW", "Revue"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("APPROVED", "Approuvé"),
                            ("REJECTED", "Rejeté"),
                            ("CANCELLED", "Annulé"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("validated_by_email", models.EmailField(blank=True, max_length=254)),
                ("validated_by_role", models.CharField(blank=True, max_length=20)),
                ("object_id", models.CharField(max_length=255)),
                ("object_repr", models.CharField(blank=True, max_length=500)),
                ("comment", models.TextField(blank=True, help_text="Commentaire du validateur")),
                (
                    "evidence",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Preuves de validation (documents, métadonnées)",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "requires_second_approval",
                    models.BooleanField(default=False, help_text="Nécessite une double validation"),
                ),
                ("second_approval_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True, help_text="Date d'expiration de la validation", null=True
                    ),
                ),
                ("is_expired", models.BooleanField(default=False)),
                ("request_id", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
                    ),
                ),
                (
                    "second_approval_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="second_validations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "validated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="validations_performed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trace de validation",
                "verbose_name_plural": "Traces de validation",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"], name="audit_valid_content_0c5e35_idx"
                    ),
                    models.Index(
                        fields=["validated_by", "-created_at"],
                        name="audit_valid_validat_607458_idx",
                    ),
                    models.Index(
                        fields=["validation_type", "status"], name="audit_valid_validat_7c782b_idx"
                    ),
                    models.Index(fields=["-created_at"], name="audit_valid_created_d5d584_idx"),
                ],
            },
        ),
    ]
